
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author rohit desai
 */

public class TEAM_SQUAD extends javax.swing.JFrame {

    Connection conn=null;
PreparedStatement pst=null;
ResultSet rs=null;
    /**
     * Creates new form TEAM_SQUAD
     */
int x,y;
    public TEAM_SQUAD() {
        initComponents();
        jTable1.setBackground(new Color(0,0,0));
        ((DefaultTableCellRenderer)jTable1.getDefaultRenderer(Object.class)).setBackground(new Color(0,0,0,0));
        jTable1.setGridColor(Color.GREEN);
        jTable1.setForeground(Color.BLACK);
        jScrollPane1.setBackground(new Color(0,0,0,0));
        jScrollPane1.setOpaque(false);
        jTable1.setOpaque(false);
        ((DefaultTableCellRenderer)jTable1.getDefaultRenderer(Object.class)).setOpaque(false);
        jScrollPane1.getViewport().setOpaque(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("TEAM_SQUAD");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("X");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("-");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("<");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 518, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel2))
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 30));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setText("INDIA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 100, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 0, 0));
        jButton2.setText("ENGLAND");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 120, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 0, 0));
        jButton3.setText("SOUTH AFRICA");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, -1, -1));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 0, 0));
        jButton4.setText("NEW ZEALAND");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, -1, -1));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 0, 0));
        jButton5.setText("SRI LANKA");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 90, 110, -1));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 51, 51));
        jButton6.setText("AFGHANISTAN");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, -1, -1));

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 51, 51));
        jButton7.setText("AUSTRALIA");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, 120, -1));

        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("TEAM SQUAD");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 200, 40));

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 51, 51));
        jButton8.setText("BANGLADESH");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 380, 120, -1));

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 51, 51));
        jButton9.setText("PAKISTAN");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 100, -1));

        jButton10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 51, 51));
        jButton10.setText("WEST INDIES");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 380, 120, -1));

        jTable1.setBackground(new java.awt.Color(0, 0, 0));
        jTable1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTable1.setForeground(new java.awt.Color(204, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SR.NO", "PLAYER NAME", "TYPE", "STRIKE RATE"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 710, 200));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RTS2LN0O.jpeg"))); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 750, 500));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 750, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         conn=myconnection.ConnectDB();
        String Sql="select * from england";
        try{
            pst=conn.prepareStatement(Sql);
            rs=pst.executeQuery();
           jTable1.setModel(new DefaultTableModel(null,new String[]{"SR.NO","PLAYER NAME","TYPE","STRIKE RATE"}));
            while(rs.next()){
                String sr=String.valueOf(rs.getInt("SR.NO"));
                String TEAM1=String.valueOf(rs.getString("PLAYER NAME"));
                String TEAM2=String.valueOf(rs.getString("TYPE"));
                String TIMING=String.valueOf(rs.getString("STRIKE RATE"));
                String tbData[]={sr,TEAM1,TEAM2,TIMING};
                DefaultTableModel tb1Model=(DefaultTableModel)jTable1.getModel();
                    
                tb1Model.addRow(tbData);
                
            }
            
            
            
        } catch (Exception e) {
        JOptionPane.showMessageDialog(rootPane, e);
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
               conn=myconnection.ConnectDB();
        String Sql="select * from afghanistan";
        try{
            pst=conn.prepareStatement(Sql);
            rs=pst.executeQuery();
           jTable1.setModel(new DefaultTableModel(null,new String[]{"SR.NO","PLAYER NAME","TYPE","STRIKE RATE"}));
            while(rs.next()){
                String sr=String.valueOf(rs.getInt("SR.NO"));
                String TEAM1=String.valueOf(rs.getString("PLAYER NAME"));
                String TEAM2=String.valueOf(rs.getString("TYPE"));
                String TIMING=String.valueOf(rs.getString("STRIKE RATE"));
                String tbData[]={sr,TEAM1,TEAM2,TIMING};
                DefaultTableModel tb1Model=(DefaultTableModel)jTable1.getModel();
                    
                tb1Model.addRow(tbData);
                
            }
            
            
            
        } catch (Exception e) {
        JOptionPane.showMessageDialog(rootPane, e);
    }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        conn=myconnection.ConnectDB();
        String Sql="select * from australia";
        try{
            pst=conn.prepareStatement(Sql);
            rs=pst.executeQuery();
           jTable1.setModel(new DefaultTableModel(null,new String[]{"SR.NO","PLAYER NAME","TYPE","STRIKE RATE"}));
            while(rs.next()){
                String sr=String.valueOf(rs.getInt("SR.NO"));
                String TEAM1=String.valueOf(rs.getString("PLAYER NAME"));
                String TEAM2=String.valueOf(rs.getString("TYPE"));
                String TIMING=String.valueOf(rs.getString("STRIKE RATE"));
                String tbData[]={sr,TEAM1,TEAM2,TIMING};
                DefaultTableModel tb1Model=(DefaultTableModel)jTable1.getModel();
                    
                tb1Model.addRow(tbData);
                
            }
            
            
            
        } catch (Exception e) {
        JOptionPane.showMessageDialog(rootPane, e);
    }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        conn=myconnection.ConnectDB();
        String Sql="select * from sri";
        try{
            pst=conn.prepareStatement(Sql);
            rs=pst.executeQuery();
           jTable1.setModel(new DefaultTableModel(null,new String[]{"SR.NO","PLAYER NAME","TYPE","STRIKE RATE"}));
            while(rs.next()){
                String sr=String.valueOf(rs.getInt("SR.NO"));
                String TEAM1=String.valueOf(rs.getString("PLAYER NAME"));
                String TEAM2=String.valueOf(rs.getString("TYPE"));
                String TIMING=String.valueOf(rs.getString("STRIKE RATE"));
                String tbData[]={sr,TEAM1,TEAM2,TIMING};
                DefaultTableModel tb1Model=(DefaultTableModel)jTable1.getModel();
                    
                tb1Model.addRow(tbData);
                
            }
            
            
            
        } catch (Exception e) {
        JOptionPane.showMessageDialog(rootPane, e);
    }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
           conn=myconnection.ConnectDB();
        String Sql="select * from bangladesh";
        try{
            pst=conn.prepareStatement(Sql);
            rs=pst.executeQuery();
           jTable1.setModel(new DefaultTableModel(null,new String[]{"SR.NO","PLAYER NAME","TYPE","STRIKE RATE"}));
            while(rs.next()){
                String sr=String.valueOf(rs.getInt("SR.NO"));
                String TEAM1=String.valueOf(rs.getString("PLAYER NAME"));
                String TEAM2=String.valueOf(rs.getString("TYPE"));
                String TIMING=String.valueOf(rs.getString("STRIKE RATE"));
                String tbData[]={sr,TEAM1,TEAM2,TIMING};
                DefaultTableModel tb1Model=(DefaultTableModel)jTable1.getModel();
                    
                tb1Model.addRow(tbData);
                
            }
            
            
            
        } catch (Exception e) {
        JOptionPane.showMessageDialog(rootPane, e);
    }     
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     conn=myconnection.ConnectDB();
        String Sql="select * from india";
        try{
            pst=conn.prepareStatement(Sql);
            rs=pst.executeQuery();
             jTable1.setModel(new DefaultTableModel(null,new String[]{"SR.NO","PLAYER NAME","TYPE","STRIKE RATE"}));
            while(rs.next()){
                String sr=String.valueOf(rs.getInt("SR.NO"));
                String TEAM1=String.valueOf(rs.getString("PLAYER NAME"));
                String TEAM2=String.valueOf(rs.getString("TYPE"));
                String TIMING=String.valueOf(rs.getString("STRIKE RATE"));
                String tbData[]={sr,TEAM1,TEAM2,TIMING};
                DefaultTableModel tb1Model=(DefaultTableModel)jTable1.getModel();
                 
                tb1Model.addRow(tbData);
                
            }
            
            
            
        } catch (Exception e) {
        JOptionPane.showMessageDialog(rootPane, e);
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
     System.exit(0);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
         this.setState(ICONIFIED);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
         int xx=evt.getXOnScreen();
        int yy=evt.getYOnScreen();
        this.setLocation(xx-x,yy-y);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
              int xx=evt.getXOnScreen();
        int yy=evt.getYOnScreen();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
       new Team().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
       conn=myconnection.ConnectDB();
        String Sql="select * from west";
        try{
            pst=conn.prepareStatement(Sql);
            rs=pst.executeQuery();
           jTable1.setModel(new DefaultTableModel(null,new String[]{"SR.NO","PLAYER NAME","TYPE","STRIKE RATE"}));
            while(rs.next()){
                String sr=String.valueOf(rs.getInt("SR.NO"));
                String TEAM1=String.valueOf(rs.getString("PLAYER NAME"));
                String TEAM2=String.valueOf(rs.getString("TYPE"));
                String TIMING=String.valueOf(rs.getString("STRIKE RATE"));
                String tbData[]={sr,TEAM1,TEAM2,TIMING};
                DefaultTableModel tb1Model=(DefaultTableModel)jTable1.getModel();
                    
                tb1Model.addRow(tbData);
                
            }
            
            
            
        } catch (Exception e) {
        JOptionPane.showMessageDialog(rootPane, e);
    }  
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
         conn=myconnection.ConnectDB();
        String Sql="select * from pakistan";
        try{
            pst=conn.prepareStatement(Sql);
            rs=pst.executeQuery();
           jTable1.setModel(new DefaultTableModel(null,new String[]{"SR.NO","PLAYER NAME","TYPE","STRIKE RATE"}));
            while(rs.next()){
                String sr=String.valueOf(rs.getInt("SR.NO"));
                String TEAM1=String.valueOf(rs.getString("PLAYER NAME"));
                String TEAM2=String.valueOf(rs.getString("TYPE"));
                String TIMING=String.valueOf(rs.getString("STRIKE RATE"));
                String tbData[]={sr,TEAM1,TEAM2,TIMING};
                DefaultTableModel tb1Model=(DefaultTableModel)jTable1.getModel();
                    
                tb1Model.addRow(tbData);
                
            }
            
            
            
        } catch (Exception e) {
        JOptionPane.showMessageDialog(rootPane, e);
    }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       conn=myconnection.ConnectDB();
        String Sql="select * from new";
        try{
            pst=conn.prepareStatement(Sql);
            rs=pst.executeQuery();
           jTable1.setModel(new DefaultTableModel(null,new String[]{"SR.NO","PLAYER NAME","TYPE","STRIKE RATE"}));
            while(rs.next()){
                String sr=String.valueOf(rs.getInt("SR.NO"));
                String TEAM1=String.valueOf(rs.getString("PLAYER NAME"));
                String TEAM2=String.valueOf(rs.getString("TYPE"));
                String TIMING=String.valueOf(rs.getString("STRIKE RATE"));
                String tbData[]={sr,TEAM1,TEAM2,TIMING};
                DefaultTableModel tb1Model=(DefaultTableModel)jTable1.getModel();
                    
                tb1Model.addRow(tbData);
                
            }
            
            
            
        } catch (Exception e) {
        JOptionPane.showMessageDialog(rootPane, e);
    } 
    }//GEN-LAST:event_jButton4ActionPerformed
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
          conn=myconnection.ConnectDB();
        String Sql="select * from south";
        try{
            pst=conn.prepareStatement(Sql);
            rs=pst.executeQuery();
           jTable1.setModel(new DefaultTableModel(null,new String[]{"SR.NO","PLAYER NAME","TYPE","STRIKE RATE"}));
            while(rs.next()){
                String sr=String.valueOf(rs.getInt("SR.NO"));
                String TEAM1=String.valueOf(rs.getString("PLAYER NAME"));
                String TEAM2=String.valueOf(rs.getString("TYPE"));
                String TIMING=String.valueOf(rs.getString("STRIKE RATE"));
                String tbData[]={sr,TEAM1,TEAM2,TIMING};
                DefaultTableModel tb1Model=(DefaultTableModel)jTable1.getModel();
                    
                tb1Model.addRow(tbData);
                
            }
            
            
            
        } catch (Exception e) {
        JOptionPane.showMessageDialog(rootPane, e);
    } 
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TEAM_SQUAD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TEAM_SQUAD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TEAM_SQUAD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TEAM_SQUAD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TEAM_SQUAD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
